In [2]:
import numpy as np
l1=[2,3,4,5,6]
arr1=np.array(l1)
print(arr1)

[2 3 4 5 6]


In [3]:
import numpy as np
a=np.array([[10,11,12,13],[21,22,23,24]])
print(a)

[[10 11 12 13]
 [21 22 23 24]]


In [4]:
import numpy as np
arr=np.empty([3,2],dtype=int)
print(arr)

[[ 170732845  538976288]
 [1981820462 1769173605]
 [1684106863  979658084]]


In [6]:
import numpy as np
arr1=np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [14]:
import numpy as np
arr1=np.arange(4,20,3)
print(arr1)

[ 4  7 10 13 16 19]


In [13]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
b=np.reshape(a,(4,2))
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
    import numpy as np 
    data=np.array([5,2,7,3,9])
    print(data[:])
    print(data[1:3])
    print(data[:2])
    print(data[-2:])

[5 2 7 3 9]
[2 7]
[5 2]
[3 9]


In [16]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[1:2,0:4]
print('b',b)
b=a[1:2,1:2]
print('b',b)
b=a[:2,0:2]
print('b',b)
b=a[:2,1:3]
print('b',b)
b=a[1:3,2:4]
print('b',b)

b [[5 6 7 8]]
b [[6]]
b [[1 2]
 [5 6]]
b [[2 3]
 [6 7]]
b [[ 7  8]
 [11 12]]


In [19]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[0:2,1:3]
print(b)
b[0,0]=20
print(b)
print(a)

[[2 3]
 [6 7]]
[[20  3]
 [ 6  7]]
[[ 1 20  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
import numpy as np
a=np.array([[7,5,9],[2,6,8]])
print(a)
b=np.array([10,10,10])
c=np.add(a,b)
print(c)
c=np.subtract(a,b)
print(c)
c=np.multiply(a,b)
print(c)
c=np.divide(a,b)
print(c)

[[7 5 9]
 [2 6 8]]
[[17 15 19]
 [12 16 18]]
[[-3 -5 -1]
 [-8 -4 -2]]
[[70 50 90]
 [20 60 80]]
[[0.7 0.5 0.9]
 [0.2 0.6 0.8]]


In [21]:
import numpy as np
x=np.arange(2,11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [24]:
import numpy as np
x=np.array([1,2,3,4])
print(x.sum())
print(x.min())
print(x.max())
print(x.mean())
print(np.median(x))

10
1
4
2.5
2.5


In [28]:
import numpy as np
arr1=np.zeros((3,3),dtype=bool)
print(arr1)

[[False False False]
 [False False False]
 [False False False]]


In [30]:
import numpy as np
x=np.ones((10,10))
print(x)
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
import numpy as np
a=np.array([[7,5],[1,6]])
print(np.concatenate([a,a]))
print(np.concatenate([a,a],axis=1))


[[7 5]
 [1 6]
 [7 5]
 [1 6]]
[[7 5 7 5]
 [1 6 1 6]]


In [40]:
import numpy as np
a=np.array([[1,2],[2,4]])
b=np.array([[7,4]])
c=np.concatenate((a,a),axis=0)
print(c)
print(a.T)

[[1 2]
 [2 4]
 [1 2]
 [2 4]]
[[1 2]
 [2 4]]
